// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvLqkRRo32UqPRzV7E-JIRryGZiDxn2aY',
    appId: '1:227527185308:web:13078874e5f3538d05ee59',
    messagingSenderId: '227527185308',
    projectId: 'feed-ac7d2',
    authDomain: 'feed-ac7d2.firebaseapp.com',
    storageBucket: 'feed-ac7d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs2J-nB2mwjdYOLBBrj07XsR0AR2luysg',
    appId: '1:227527185308:android:ca886e4ffc70bb1d05ee59',
    messagingSenderId: '227527185308',
    projectId: 'feed-ac7d2',
    storageBucket: 'feed-ac7d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh_fw5kOWId1Q8vTgAkS1VHj_dqxU4waY',
    appId: '1:227527185308:ios:0a394d97615f862105ee59',
    messagingSenderId: '227527185308',
    projectId: 'feed-ac7d2',
    storageBucket: 'feed-ac7d2.firebasestorage.app',
    iosBundleId: 'com.iti.feed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh_fw5kOWId1Q8vTgAkS1VHj_dqxU4waY',
    appId: '1:227527185308:ios:0a394d97615f862105ee59',
    messagingSenderId: '227527185308',
    projectId: 'feed-ac7d2',
    storageBucket: 'feed-ac7d2.firebasestorage.app',
    iosBundleId: 'com.iti.feed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvLqkRRo32UqPRzV7E-JIRryGZiDxn2aY',
    appId: '1:227527185308:web:b53a3da8f4df8e6005ee59',
    messagingSenderId: '227527185308',
    projectId: 'feed-ac7d2',
    authDomain: 'feed-ac7d2.firebaseapp.com',
    storageBucket: 'feed-ac7d2.firebasestorage.app',
  );
}
